modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "enigmaticaddons"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "logo.png"

[[dependencies.enigmaticaddons]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.enigmaticaddons]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.enigmaticaddons]]
    modId = "enigmaticlegacy"
    mandatory = true
    versionRange = "[2.30.1,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.enigmaticaddons]]
    modId = "curios"
    mandatory = true
    versionRange = "[1.19.2-5.1.1.0,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.enigmaticaddons]]
    modId = "patchouli"
    mandatory = true
    versionRange = "[1.19.2-77,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.enigmaticaddons]]
    modId = "caelus"
    mandatory = true
    versionRange = "[1.19.2-3.0.0.6,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.enigmaticaddons]]
    modId = "jei"
    mandatory = false
    versionRange = "[15.19.0,)"
    ordering = "NONE"
    side = "CLIENT"